# typed: strong
# This is an autogenerated file for Rails' mailers.
# Please rerun bundle exec rake rails_rbi:mailers to regenerate.
class UserMailer
  sig { params(email: T.untyped, raw: T.untyped).returns(ActionMailer::MessageDelivery) }
  def self.account_reset(email, raw); end
end
